name: main

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: ghcr.io/chuhlomin/timestamp

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push to CR
        uses: chuhlomin/actions/docker-build-push@main
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_TOKEN }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Deploy to GKE
        uses: chuhlomin/actions/deploy-gke@main
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          cluster_name: cluster-1
          location: us-central1-c
          template_path: kube.template.yml
          vars: |
            app: timestamp
            image: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            domain: ts.chuhlomin.com
          rollout_status_wait: deployment/timestamp
