name: main

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        run: |
          mkdir output
          mv index.html copy.png favicon.png og.png favicon.ico likely.css likely.js output

      - name: Make screenshot
        if: false
        uses: chuhlomin/actions/screenshot@main
        with:
          url: file://${{github.workspace}}/output/index.html
          mode: page
          output: screenshot.png
          width: 600
          height: 600
          deviceScaleFactor: 2
          cornerRadius: 20
          addShadow: true
          uploadArtifact: ${{ github.event_name == 'pull_request' }}
          commit: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

      - name: Deploy
        uses: cloudflare/wrangler-action@v3.14.1
        if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip deploy]')
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy output --project-name=timestamp --branch=main --commit-dirty=true
